config/routes.rb
Rails.application.routes.draw do
  resources :email_adresses
  resources :phone_numbers
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_adress.rb
class EmailAdress < ApplicationRecord
  belongs_to :person, optional: true
  validates :adress, :person_id, presence: true  
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :phone_numbers
  has_many :email_adresses
  validates :first_name, :last_name, presence: true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :person, optional: true
  validates :number, :person_id, presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/email_adresses_controller.rb
class EmailAdressesController < ApplicationController
  before_action :set_email_adress, only: [:show, :edit, :update, :destroy]

  # GET /email_adresses
  # GET /email_adresses.json
  def index
    @email_adresses = EmailAdress.all
  end

  # GET /email_adresses/1
  # GET /email_adresses/1.json
  def show
  end

  # GET /email_adresses/new
  def new
    @email_adress = EmailAdress.new(person_id: params[:person_id])
  end

  # GET /email_adresses/1/edit
  def edit
  end

  # POST /email_adresses
  # POST /email_adresses.json
  def create
    @email_adress = EmailAdress.new(email_adress_params)

    respond_to do |format|
      if @email_adress.save
        format.html { redirect_to @email_adress.person, notice: 'Email adress was successfully created.' }
        format.json { render :show, status: :created, location: @email_adress }
      else
        format.html { render :new }
        format.json { render json: @email_adress.errors, status: :unprocessable_entity }
      end
    end    
  end

  # PATCH/PUT /email_adresses/1
  # PATCH/PUT /email_adresses/1.json
  def update
    respond_to do |format|
      if @email_adress.update(email_adress_params)
        format.html { redirect_to @email_adress.person, notice: 'Email adress was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_adress }
      else
        format.html { render :edit }
        format.json { render json: @email_adress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_adresses/1
  # DELETE /email_adresses/1.json
  def destroy
    i = @email_adress.person_id.clone
    @email_adress.destroy
    respond_to do |format|
      format.html { redirect_to people_url+"/"+i.to_s, notice: 'Email adress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_adress
      @email_adress = EmailAdress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_adress_params
      params.require(:email_adress).permit(:adress, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new(person_id: params[:person_id])
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.person, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.person, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    i = @phone_number.person_id.clone
    @phone_number.destroy
    respond_to do |format|
      # format.html { redirect_to "people/" + i.to_s, notice: 'Phone number was successfully destroyed.' }
      format.html { redirect_to people_url+"/"+i.to_s, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:number, :person_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_adresses_helper.rb
module EmailAdressesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/email_adresses/_form.html.erb
<%= form_with(model: email_adress, local: true) do |form| %>
  <% if email_adress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(email_adress.errors.count, "error") %> prohibited this email_adress from being saved:</h2>

      <ul>
      <% email_adress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :adress %>
    <%= form.text_field :adress, id: :email_adress_adress %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.number_field :person_id, id: :email_adress_person_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/email_adresses/edit.html.erb
<h1>Editing Email Adress</h1>

<%= render 'form', email_adress: @email_adress %>

<%= link_to 'Show', @email_adress %> |
<%= link_to 'Back', email_adresses_path %>

app/views/email_adresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Email Adresses</h1>

<table>
  <thead>
    <tr>
      <th>Adress</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_adresses.each do |email_adress| %>
      <tr>
        <td><%= email_adress.adress %></td>
        <td><%= email_adress.person_id %></td>
        <td><%= link_to 'Show', email_adress %></td>
        <td><%= link_to 'Edit', edit_email_adress_path(email_adress) %></td>
        <td><%= link_to 'Destroy', email_adress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email Adress', new_email_adress_path %>

app/views/email_adresses/new.html.erb
<h1>New Email Adress</h1>

<%= render 'form', email_adress: @email_adress %>

<%= link_to 'Back', email_adresses_path %>

app/views/email_adresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adress:</strong>
  <%= @email_adress.adress %>
</p>

<p>
  <strong>Person:</strong>
  <%= @email_adress.person_id %>
</p>

<%= link_to 'Edit', edit_email_adress_path(@email_adress) %> |
<%= link_to 'Back', email_adresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :person_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :person_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>
<p>Phone</p>
<ul>
  <% @person.phone_numbers.each do |phone| %>
    <li><%= phone.number %> <%= link_to('edit', edit_phone_number_path(phone)) %>
      
    </li><%= link_to('delete', phone_number_path(phone), :method => "delete") %>

  <% end %>
</ul>
<p>Mail</p>
<ul>
  <% @person.email_adresses.each do |a| %>
    <li><%= a.adress %>   <%= link_to('edit', edit_email_adress_path(a)) %>    
    </li><%= link_to('delete', email_adress_path(a), :method => "delete") %>
  <% end %>
</ul>


<%= link_to 'Add phone number', new_phone_number_path(person_id: @person.id) %> |
<%= link_to 'Add email adress', new_email_adress_path(person_id: @person.id) %> |
<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/phone_numbers/_form.html.erb
<%= form_with(model: phone_number, local: true) do |form| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :phone_number_number %>
  </div>

  <div class="field">
    <%= form.label :person_id %>
    <%= form.number_field :person_id, id: :phone_number_person_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.number %></td>
        <td><%= phone_number.person_id %></td>
        <td><%= link_to 'Show', phone_number %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @phone_number.number %>
</p>

<p>
  <strong>Person:</strong>
  <%= @phone_number.person_id %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>